name: BadAppleRealtime
version: '1.0-SNAPSHOT'
main: tr.com.salihefee.badapplerealtime.BadApple
api-version: '1.20'
commands:
  badappler:
    usage: /badappler <videoName>
    description: Plays the video specified.
  cancelr:
    usage: /cancelr
    description: Stops playback.
  extractr:
    usage: /extractr <videoPath> <size>